"""empty message

Revision ID: bc2a9617001c
Revises: 05f1ec9c855f
Create Date: 2022-08-13 23:57:18.557155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2a9617001c'
down_revision = '05f1ec9c855f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Venue', ['venue_id'], ['id'])
    op.add_column('Venue', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'artist_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'venue_id')
    # ### end Alembic commands ###
